on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-raft:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lab: [ "4A" ] 
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Run Tests
      run: |
        cd src/kvraft1/rsm
        go test -v -race -run ${{ matrix.lab }}